version: '3.8'
services:
  mongo:
#    container_name: MongoDB
    image: mongo:latest
    #restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - /Users/clear/Development/mongo_data/latest:/data/db